server:
  port: 8888

management:
  context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
spring:
  cloud:
    config:
      server:
        uri: https://github.com/RussellRC/RedisTestCloudProperties